# Example bqdo config (TOML)

directory = "sql/"
project_id = ""
dataset = "bqdo_example"
location = "US"
impersonate_service_account = ""

[vars]
env = "dev"
run_id = "example_{{ .env }}"
start_date = "2025-01-01"

